// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/activity": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil daftar kegiatan milik user yang sedang login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Daftar Semua Kegiatan User",
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Membuat rencana kegiatan baru milik user yang sedang login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Buat Rencana Kegiatan",
                "parameters": [
                    {
                        "description": "Data JSON Kegiatan",
                        "name": "activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project-telkom-sigma_internal_models.Activity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/project-telkom-sigma_internal_models.Activity"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/activity/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus kegiatan milik user yang sedang login",
                "tags": [
                    "Activity"
                ],
                "summary": "Hapus Kegiatan",
                "responses": {}
            }
        },
        "/api/activity/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengubah data kegiatan milik user yang sedang login",
                "tags": [
                    "Activity"
                ],
                "summary": "Perbarui Kegiatan",
                "responses": {}
            }
        },
        "/api/login": {
            "post": {
                "description": "Autentikasi user dan mendapatkan JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Data Login",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project-telkom-sigma_internal_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/register": {
            "post": {
                "description": "Mendaftarkan user baru ke dalam sistem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User Register",
                "parameters": [
                    {
                        "description": "Data User (Username \u0026 Password)",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project-telkom-sigma_internal_models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/weather": {
            "get": {
                "description": "Mengambil semua data cuaca yang telah di-sync, diurutkan berdasarkan waktu sinkronisasi terbaru",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Weather"
                ],
                "summary": "Daftar Semua Data Cuaca",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project-telkom-sigma_internal_models.Weather"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/weather/dashboard": {
            "get": {
                "description": "Mengambil data agregasi untuk Pie Chart (Kategori) dan Column Chart (Suhu Harian)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Data Statistik Dashboard",
                "responses": {
                    "200": {
                        "description": "Contoh: {pie_chart: [], column_chart: []}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/weather/delete": {
            "delete": {
                "tags": [
                    "Weather"
                ],
                "summary": "Hapus Data Cuaca",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Weather",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/weather/detail": {
            "get": {
                "tags": [
                    "Weather"
                ],
                "summary": "Detail Data Cuaca",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Weather",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/weather/sync": {
            "post": {
                "description": "Mengambil data cuaca dari API BMKG berdasarkan kode wilayah (adm4) dan menyimpannya ke database",
                "tags": [
                    "Weather"
                ],
                "summary": "Sinkronisasi Data BMKG",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode Wilayah (contoh: 31.71.01.1001)",
                        "name": "adm4",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/weather/update": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Weather"
                ],
                "summary": "Update Data Cuaca",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Weather",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Data Weather",
                        "name": "weather",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project-telkom-sigma_internal_models.Weather"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/wilayah": {
            "get": {
                "description": "Mengambil data wilayah untuk dropdown search",
                "tags": [
                    "Wilayah"
                ],
                "summary": "Daftar Wilayah (ADM4)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cari kode atau nama wilayah",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project-telkom-sigma_internal_models.Wilayah"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Endpoint untuk memastikan backend berjalan lancar",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Cek Status Server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "project-telkom-sigma_internal_models.Activity": {
            "type": "object",
            "properties": {
                "activity_date": {
                    "type": "string",
                    "example": "2026-02-27T10:00:00Z"
                },
                "area_code": {
                    "type": "string",
                    "example": "31.71.01.1001"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "Rapat Koordinasi"
                },
                "user_id": {
                    "type": "integer"
                },
                "wilayah": {
                    "$ref": "#/definitions/project-telkom-sigma_internal_models.Wilayah"
                }
            }
        },
        "project-telkom-sigma_internal_models.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "project-telkom-sigma_internal_models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-03-07T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "password": {
                    "type": "string",
                    "example": "secret123"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-03-07T00:00:00Z"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "project-telkom-sigma_internal_models.Weather": {
            "type": "object",
            "properties": {
                "analysis_date": {
                    "type": "string"
                },
                "area_code": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "hu": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "local_datetime": {
                    "type": "string"
                },
                "sync_time": {
                    "type": "string"
                },
                "t": {
                    "type": "number"
                },
                "tcc": {
                    "type": "integer"
                },
                "utc_datetime": {
                    "type": "string"
                },
                "vs_text": {
                    "type": "string"
                },
                "wd": {
                    "type": "string"
                },
                "weather_desc": {
                    "type": "string"
                },
                "weather_desc_en": {
                    "type": "string"
                },
                "wilayah": {
                    "$ref": "#/definitions/project-telkom-sigma_internal_models.Wilayah"
                },
                "ws": {
                    "type": "number"
                }
            }
        },
        "project-telkom-sigma_internal_models.Wilayah": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "loc": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API Sistem Informasi Telkom Sigma",
	Description:      "Dokumentasi API untuk Proyek Internal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
